inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.7.3
  DisplayCopNames: true
  Exclude:
    - 'spec/internal_test_hyrax/**/*'
    - 'vendor/**/*'
Metrics/BlockLength:
  Max: 80
  Exclude:
    - 'spec/**/*.rb'
    -
RSpec/ExampleLength:
  Max: 25

Layout/LineLength:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/config/hyrax_events_spec.rb'

Style/FrozenStringLiteralComment:
  Enabled: true

RSpec/LetSetup:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
